worktree:
  base_dir: .worktrees
  copy_files: []

multiplexer:
  type: tmux
  session_prefix: dict-skills
  start_in_session: true

agent:
  type: "pi"
  args:
    - --provider
    - anthropic
    - --model
    - claude-sonnet-4-5

parallel:
  max_concurrent: 2

workflow:
  name: default
  steps:
    - plan
    - implement
    - test
    - review
    - merge

workflows:
  quick:
    description: "Quick validation - linting and type checking only (no tests)"
    steps:
      - plan
      - implement
      - review
    context: |
      Bun + TypeScript crawler project. Quick workflow for rapid feedback.
      Working directory: link-crawler/
      Run: bun run check (Biome lint) and bun run typecheck (TypeScript)

  thorough:
    description: "Complete workflow - full validation with tests and documentation review"
    steps:
      - plan
      - implement
      - test
      - review
      - merge
    context: |
      Bun + TypeScript web crawler (dict-skills).

      **Tech Stack:**
      - Runtime: Bun 1.0+
      - Linter: Biome (bun run check)
      - Type Checker: tsc (bun run typecheck)
      - Test Framework: Vitest (bun run test)
      - Browser Automation: Playwright CLI 0.0.63+

      **Key Constraints:**
      - Playwright-cli 0.0.63+: Default session mandatory (no parallel crawling)
      - SessionId short format (Unix socket path length limit)
      - Single-threaded crawler execution

      **Development in link-crawler/:**
      - src/ - Core implementation (crawler, parser, diff, output, utils)
      - tests/ - Unit and integration tests
      - Commands: check, typecheck, test

      **Design Principles:**
      - Unified playwright-cli approach (no SPA branching)
      - AI-first Markdown output (full.md for LLM context)
      - Hash-based differential crawling (--diff flag)

  test:
    description: "Test-focused workflow - comprehensive testing with integration checks"
    steps:
      - plan
      - implement
      - test
      - review
    context: |
      dict-skills test workflow. Focus on test quality and coverage.

      **Test Setup (link-crawler/):**
      - Unit tests: tests/unit/
      - Integration tests: tests/integration/
      - Global teardown: tests/global-teardown.ts
      - Config: vitest.config.ts

      **Commands:**
      - Full tests: bun run test
      - With coverage: npm run test -- --coverage (outputs to coverage/)

      **Integration Testing:**
      - Manual crawler: bun run src/crawl.ts https://example.com -d 1
      - Verify .context/ output format (pages/, chunks/, full.md)
      - Test diff mode: --diff flag behavior

  crawler-dev:
    description: "Crawler-specific development - focus on crawler logic and Playwright integration"
    steps:
      - plan
      - implement
      - test
      - review
    context: |
      Crawler development workflow. Focus on crawler components.

      **Core Components (link-crawler/src/):**
      - crawler/ - Browser automation and crawling logic
      - parser/ - HTML/DOM parsing and content extraction
      - diff/ - Hash-based change detection
      - output/ - Markdown formatting and file generation

      **Integration Points:**
      - Playwright CLI: Default session mode (0.0.63+)
      - Output format: Pages + Chunks + Full.md (AI context optimized)

      **Testing Changes:**
      1. Unit tests: bun run test
      2. Integration: bun run src/crawl.ts <url> -d <depth>
      3. Diff mode: --diff flag
      4. Verify: .context/<site>/ output structure

      **Maintain Design:**
      - Keep playwright-cli unified (no branching for SPA vs static)
      - Preserve AI-friendly output format
      - Keep diff engine functional for incremental updates

  docs:
    description: "Documentation - update documentation and decision logs"
    steps:
      - plan
      - implement
      - review
    context: |
      Documentation workflow for dict-skills.

      **Main Documents:**
      - README.md - Project overview (English + Japanese)
      - link-crawler/{README.md, SKILL.md} - Crawler documentation
      - docs/cli-spec.md - Complete CLI reference with examples
      - docs/design.md - Architecture and data structures
      - docs/development.md - Developer setup and workflow
      - AGENTS.md - AI context and constraints (Japanese)

      **Decision Logs:**
      - docs/decisions/001-playwright-cli-session.md - Session constraints
      - Add new decisions as 002-, 003-, etc.

      **Update Guidelines:**
      - CLI changes → docs/cli-spec.md
      - Architecture changes → docs/design.md
      - New constraints → docs/decisions/ and AGENTS.md
      - Major findings → AGENTS.md (keep concise with links to decisions/)

plans:
  keep_recent: 10
  dir: docs/plans

improve_logs:
  keep_recent: 10
  keep_days: 7
  dir: .improve-logs

github:
  include_comments: true
  max_comments: 10
